# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Sérgio Isidoro"
description:        ""

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                ""
author:             "gfjaru"
twitter:
  username:         "smaisidoro"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/"
  - name:           "Blog"
    href:           "/blog"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

social:
  stackoverflow: 2943164
  github: sergioisidoro
  twitter: smaisidoro
  facebook: sergio.isidoro
  linkedin: sergioisidoro

gems:
  - jekyll-seo-tag
